### ISSUE TITLE
Email notifications for actions inside the application

### ISSUE THREAD

**Issue by sachindoddaguni** [sachindoddaguni/application-tracking-system#2]
Provide email notification functionality for various actions inside the application

**Comment by amoghmahesh14** [comment]
Made the following changes:

- Added email id field to the User Model. Now user needs to provide an email ID while signing up which is stored along with his details in the database.
- Whenever an application is added, updated or deleted the user is notified regarding the change via an email.
- If the application is not yet submitted, the user will be reminded about it through an email every hour.
